channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - radiant-mlhub >=0.1.3,<1.0.0
  - rasterio >=1.2,<2
  - fiona
  - shapely
  - geopandas
  - arrow
  - boto3
  - pyproj
  - keras==2.4.3
  - tensorflow-hub
  - seaborn
  - scikit-learn
  - pandas
  - numpy
  - matplotlib
  - jupyter
  - scipy >=1.4.1,<1.5
  - scikit-image >=0.16.2,<0.17
  - pytorch >=1.7.0,<1.8
  - Pillow >=8.1.0,<8.2
  - pip
  - pip:
    - tensorflow >=2.4.1,<2.5